title: Optivize
description: "Enhance Operational Efficiency"
owner_name: Zafeer
github_username: ZafeerA123
github_repo: "optivize_frontend" 
baseurl: "/optivize_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-jupyter-notebook
header_pages:
  - navigation/calendar.md
  - navigation/tutor.html
  - navigation/flashcards.md
  - navigation/productprediction.md
  - navigation/about.md
  - navigation/blog.md
exclude:
  - venv/
  - .git/
  - node_modules/
  - _site/
  




Server: https://optivize.stu.nighthawkcodingsociety.com/
Domain: nighthawkcodingsociety.com
Subdomain: optivize